---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: csv-creator-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: node-nodeclaim-reader
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["karpenter.sh"]
  resources: ["nodeclaims"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: csv-creator-binding
subjects:
- kind: ServiceAccount
  name: csv-creator-sa
  namespace: default
roleRef:
  kind: ClusterRole
  name: node-nodeclaim-reader
  apiGroup: rbac.authorization.k8s.io