apiVersion: v1
kind: Pod
metadata:
  name: csv-creator
spec:
  serviceAccountName: csv-creator-sa
  containers:
  - name: csv-creator
    image: <Update with Container Image>
    resources:
      requests:
        cpu: "10"
        memory: "20Gi"
      limits:
        cpu: "10"
        memory: "20Gi"
    volumeMounts:
    - name: data-volume
      mountPath: /app
  tolerations:
  - key: "CriticalAddonsOnly"
    operator: "Exists"
    effect: "NoSchedule"
  volumes:
  - name: data-volume
    emptyDir: {}
  priorityClassName: system-cluster-critical
