---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: karpenter-status-poller
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: karpenter-status-poller
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["karpenter.sh"]
  resources: ["nodeclaims"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: karpenter-status-poller
subjects:
- kind: ServiceAccount
  name: karpenter-status-poller
  namespace: default
roleRef:
  kind: ClusterRole
  name: karpenter-status-poller
  apiGroup: rbac.authorization.k8s.io